### ISSUE TITLE
Doesn't build under macOS Monterey 12.0.1

### ISSUE THREAD

**Issue by snakebyte69** [paulscottrobson/cerberus-2080#1]
I tried all the make files in each Sub Directory.
I'm assuming emulator it's meant to be built from the "emulator" directory. I get the following.

% make
make -C ../programs
ruby export.rb
cp *.h ../emulator/include
make -C ../cpu/z80
ruby generate.rb
make -C ../cpu/6502
python process.py
cp ../cpu/z80/code/*.h cpu/z80
cp ../cpu/6502/*.h cpu/6502
% 

If I try to build the "libraries" directory I get this

% make
ruby makeruntime.rb kernel xsprites
makeruntime.rb:19: syntax error, unexpected .., expecting ']'
			if l[..1] == ";;"
makeruntime.rb:32: else without rescue is useless
			else 
makeruntime.rb:36: syntax error, unexpected end, expecting end-of-input
make: *** [all] Error 1
% 

Same when I try to build the "m8cc" directory

% make
make -C libraries
ruby makeruntime.rb kernel xsprites
makeruntime.rb:19: syntax error, unexpected .., expecting ']'
			if l[..1] == ";;"
makeruntime.rb:32: else without rescue is useless
			else 
makeruntime.rb:36: syntax error, unexpected end, expecting end-of-input
make[1]: *** [all] Error 1
make: *** [runtime] Error 2
%

**Comment by paulscottrobson** [comment]
I've never tried to build it on a Mac though it should work. I'm using Ruby 3.0, are you using an older one ?

**Comment by snakebyte69** [comment]
I've updated to Ruby 3.0.3
Now I get this

% make
m8cc gridrunner.m8
../emulator/cerberus a80.bin go
../emulator/cerberus: ../emulator/cerberus: cannot execute binary file
make: *** [run] Error 126
% 

% make
make -C ../runtime
zasm -u -w -b runtime.asm
assembled file: runtime.asm
    551 lines, 2 passes, 0.0085 sec.
    no errors

python makeruntime.py
Traceback (most recent call last):
  File "makeruntime.py", line 30, in <module>
    h.write("\t\t\t\"base.address\":0x{0:04x}\n".format(rom[1]+rom[2]*256))
ValueError: Unknown format code 'x' for object of type 'str'
make[1]: *** [runtime] Error 1
make: *** [all] Error 2
%

% make
zasm -u -w -b runtime.asm
assembled file: runtime.asm
    551 lines, 2 passes, 0.0082 sec.
    no errors

python makeruntime.py
Traceback (most recent call last):
  File "makeruntime.py", line 30, in <module>
    h.write("\t\t\t\"base.address\":0x{0:04x}\n".format(rom[1]+rom[2]*256))
ValueError: Unknown format code 'x' for object of type 'str'
make: *** [runtime] Error 1
%

**Comment by paulscottrobson** [comment]
So am I (3.03)

The binary is a linux one, so should need recompiling for a Mac, but it *should* work ; it's just straightforward SDL2.
For the make try make -B because the makefile is a bit of a bodge and the dependencies aren't quite right.

The Python error is missing a backslash, the quotes around "base.address" in the source should be prefixed with backslashes, and are in my source ?

Can you send me the exact file you are trying to run in makeruntime.rb as an attachment ? It runs fine on mine and I can't see why it shouldn't. 

Please note this is on hold until I get my actual Cerberus. The UDG redefinition thing should work, but it might produce shedloads of snow

**Comment by cstrotm** [comment]
I was able to compile (and run) the emulator on MacOS 12.4 Monterey (M1Pro). I had to replace "python" with "python3" in [cpu](https://github.com/paulscottrobson/cerberus-2080/tree/main/cpu)/[6502](https://github.com/paulscottrobson/cerberus-2080/tree/main/cpu/6502)/Makefile
